### ISSUE TITLE
timeout does not work for slow responses

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#60]
**Description**
the `timeout` that can be specified in the `options` only applies to the connection/first-byte response time, but not to the overall response time. if the caller wants to limit the time fetch spends downloading a resource, this is not possible.

**To Reproduce**
```js
it('handles dripped response', async() => {
  const context = fetchAPI.context({
    // httpProtocol: 'http1',
    // httpsProtocols: ['http1'],
  });
  try {
    const resp = await context.fetch('https://httpbin.org/drip?duration=10&numbytes=10&code=200&delay=1', {
      cache: 'no-store',
      redirect: 'follow',
      timeout: 3000,
    });
    const text = await resp.text();
    console.log(resp.ok, resp.status, resp.headers, text);
    assert.fail('should timeout');
  } catch (e) {
    console.error(e);
    // ok!
  } finally {
    await context.disconnectAll();
  }
}).timeout(5000);
```

**Expected behavior**
the request should timeout and the test should pass.

**Comment by stefan-guggisberg** [comment]
The current behaviour is consistent with `request`, `phin` and other HTTP client modules, i.e. the timeout only applies up to the point where the response headers are received.  I therefore don't consider it a bug. 

Due to these shortcomings I have deprecated the non-standard `timeout` option and provided the standard API AbortController as a standard-compliant alternative, see #64. 

See https://github.com/adobe/helix-fetch/blob/master/test/index.test.js#L440-L457 for an equivalent test case using abort signal.
